[workspace]
resolver = "2"
members = [
    "programs/*"
]
exclude = [
    "rust-sdk",
    "ts-sdk",
    "docs",
    "examples"
]

[profile.release]
overflow-checks = false

[dependencies]
bytemuck = "1.25.0"  # Relax version pin, e.g., from "=1.22.0" to "1.23"
